name: Commit Phase

on:
    workflow_dispatch:
    push:
        branches: [main, deployment-29-10-24]

jobs:
    build-test-lint:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository 
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test:unit



