name: Run E2E Tests

on:
    workflow_dispatch:

env:
    NODE_ENV: staging

jobs:
    test-e2e:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository 
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Start DB
              run: npm run start:db:dev --workspace=@dddforum/backend

            - name: Prepare DB
              run: npm run db:prepare:dev --workspace=@dddforum/backend

            - name: Test
              run: npm run test:e2e:back



